#!/usr/bin/env python
# coding=utf8

import fontforge
from argparse import ArgumentParser

# Setup and parse the comand-line arguments
parser = ArgumentParser()
parser.add_argument("--input", help="input file name")
parser.add_argument("--output", help="output file name")
parser.add_argument("--name", help="font name")
parser.add_argument("--style", help="font style")
parser.add_argument("--version", help="(optional) text to add to the existing version")
args = parser.parse_args()

# Configure names
isMono = (True if ("Mono" in args.input) else False)
if isMono:
    fontname="{} {} Nerd Font Complete Mono".format(args.name, args.style)
    familyname="{} Nerd Font Mono".format(args.name)
else:
    fontname="{} {} Nerd Font Complete".format(args.name, args.style)
    familyname="{} Nerd Font".format(args.name)
print("Cleaning up font: {}…".format(fontname))

# Rename the file
file=fontforge.open(args.input)
if isMono:
    file.fontname="{}NerdFontCM-{}".format(args.name, args.style).replace(" ", "")
else:
    file.fontname="{}NerdFontC-{}".format(args.name, args.style).replace(" ", "")
file.familyname=familyname
file.fullname=fontname
file.appendSFNTName("English (US)", "Preferred Family", familyname)
file.appendSFNTName("English (US)", "Compatible Full", fontname)
file.appendSFNTName("English (US)", "UniqueID", fontname)
#file.appendSFNTName("English (US)", "Trademark", "")

# Mix our version information in
file.sfntRevision = None # Auto-set (refreshed) by fontforge
file.appendSFNTName("English (US)", "Version", args.version)
file.version = args.version

# Save
file.generate(args.output)
print("Generated '{}' successfully.".format(args.output))
